### ISSUE TITLE
[autoware_map_msgs] None = 0 SyntaxError: cannot assign to None

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/messages#1]
**概要**
- Reference: [rqt_publisher Segmentation Failure - ROS - kinetic](https://answers.ros.org/question/342639/rqt_publisher-segmentation-failure-ros-kinetic/)

- このリポジトリをクローンすると、rqt_publisherが下記のエラーで落ちるようになる
```bash
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_publisher/publisher_widget.py", line 105, in _update_thread_run
    message_class = roslib.message.get_message_class(base_type_str)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/message.py", line 112, in get_message_class
    cls = genpy.message.get_message_class(message_type, reload_on_error=reload_on_error)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 697, in get_message_class
    cls = _get_message_or_service_class('msg', message_type, reload_on_error=reload_on_error)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 644, in _get_message_or_service_class
    pypkg = __import__('%s.%s' % (package, type_str))
  File "/home/username/wheeltec_ws/devel/lib/python2.7/dist-packages/autoware_map_msgs/msg/__init__.py", line 9, in <module>
    from ._LaneRelation import *
  File "/home/username/wheeltec_ws/devel/lib/python2.7/dist-packages/autoware_map_msgs/msg/_LaneRelation.py", line 33
    None = 0
SyntaxError: cannot assign to None
```

該当箇所は以下
https://github.com/sbgisen/messages/blob/e6fdf7736eafe8b35e148cc4a8a3b487f2d51a93/autoware_map_msgs/msg/LaneChangeRelation.msg#L5
https://github.com/sbgisen/messages/blob/e6fdf7736eafe8b35e148cc4a8a3b487f2d51a93/autoware_map_msgs/msg/LaneRelation.msg#L4

**Comment by nyxrobotics** [comment]
Reference: https://answers.ros.org/question/342639/rqt_publisher-segmentation-failure-ros-kinetic/
